name: Find Media on TMDB
on:
  issues:
    - opened
jobs:
  get_media_meta:
    name: "Get Media Metadata"
    outputs: 
      ${{ steps.dl_meta.outputs.metadata }}
    steps:
      - uses: actions/checkout@v3
      - name: "Download Metadata"
        id: dl_meta
        env: 
          TMDB_TOKEN: ${{ secrets.TMDB_TOKEN }}
        run: |
          echo "metadata=$(node ./tmdb-search.js '${{ github.event.issue.title }}')" >> $GITHUB_OUTPUT

