name: Find Media on TMDB
on:
  issues:
    types:
      - opened

jobs:
  get_meta:
    runs-on: ubuntu-latest
    env: 
      TMDB_TOKEN: ${{ secrets.TMDB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: node ./add-data-to-project.js '${{ github.event.issue.number }}'
